<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://schedulerServices" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://schedulerServices" xmlns:intf="http://schedulerServices" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://schedulerServices" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="bid">
    <complexType/>
   </element>
   <element name="bidResponse">
    <complexType>
     <sequence>
      <element name="bidReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="bidResponse">

      <wsdl:part element="impl:bidResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="bidRequest">

      <wsdl:part element="impl:bid" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="bidScheduler">

      <wsdl:operation name="bid">

         <wsdl:input message="impl:bidRequest" name="bidRequest">

       </wsdl:input>

         <wsdl:output message="impl:bidResponse" name="bidResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="bidSchedulerSoapBinding" type="impl:bidScheduler">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="bid">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="bidRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="bidResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="bidSchedulerService">

      <wsdl:port binding="impl:bidSchedulerSoapBinding" name="bidScheduler">

         <wsdlsoap:address location="http://localhost:8080/ebayServices/services/bidScheduler"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
